### ISSUE TITLE
make sure intro aligns with any new sections added or removed.

### ISSUE THREAD

**Issue by mzettersten** [langcog/peekbank-paper#18]
Currently, the introduction lays out a series of questions that the vignettes only partially address  - once the vignettes are finalized, we'll need to make sure that the intro sets up the "right" expectations/ is consistent with the vignettes (e.g. swingley currently isn't exactly a reproducibility section, so maybe needs some tweaking to align with that framing; no vignette on power/ replicability-related issues).

**Comment by mcfrank** [comment]
#wontfix
